#!/usr/bin/env bash

set -euo pipefail
doas true

nix fmt

git --no-pager diff

run() {
    doas nixos-rebuild \
        switch \
        --print-build-logs \
        --accept-flake-config \
        --flake .# \
        "$@"
}

if which nom >/dev/null; then
    run --verbose \
        --log-format internal-json \
        "$@" \
    |& nom --json
else
    run "$@"
fi

notify-send "System update done" || true
